### ISSUE TITLE
About train_ClsConfSet.lst

### ISSUE THREAD

**Issue by MyeongJin-Kim** [yzou2/CRST#16]
In your code, train_ClsConfSet.lst only contains 505 images. Is there any reason you didn't used 2975 images for pseudo label generation?

**Comment by yzou2** [comment]
Thanks a lot for your interest in our work.

The train_ClsConfSet.lst is a subset of the whole cityscapes training list. It is first used in CBST (https://github.com/yzou2/CBST). The results on CRST/CBST is produced by this subset. In our ECCV paper, I tried UDA with the full train-set, but the performance is slightly worse than using the ClsConfSet.

Intuitively, we assume that not all images in Cityscapes are overall good enough for generating pseudo-labels since some images have overall bad predictions/pseudo-labels and lots of false positives. If we can first select these good images, we may have better adaptation performance. Thus we select the subset according to a score called class balanced score (CBS). CBS is defined for each image. The score captures the global prediction confidence for an image, considering the class-balance. For computing CBS, first get the average of pixel-level prediction confidence for each class in one image, then get the mean of the class-wise average confidence. After getting all CBS of cityscapes train-set, we set a threshold to select the ClsConfSet. Hope this can answer your questions.
