### ISSUE TITLE
Regularizer weight in MRKLD

### ISSUE THREAD

**Issue by xiaoaoran** [yzou2/CRST#38]
Hi,

In your paper, the regularizer weight **mr_weight_kld** is set as 0.1 for MRKLD. But I found when calculating kld distance, you multipled the logsoftmax with another weight **reg_weights** which is also 0.1.  So the overall weight for the regularization term is 0.1*0.1=0.01.

May I know what is this 'reg_weighs' https://github.com/yzou2/CRST/blob/f7e4df0f9310d3a1ce583602a6a2064c4d7a6483/crst_seg.py#L858

https://github.com/yzou2/CRST/blob/f7e4df0f9310d3a1ce583602a6a2064c4d7a6483/crst_seg.py#L861

**Comment by yzou2** [comment]
Thanks for catching up. If I remember correctly, we find the hyperparameters chosen in the repo achieves better performance than the paper. That's why we choose it. The reg_weights are hyperparameters to control if we apply regularization on source or target samples (https://github.com/yzou2/CRST/blob/f7e4df0f9310d3a1ce583602a6a2064c4d7a6483/crst_seg.py#L344-L348): mr_weight_src = 0 means we do not apply MRKLD regularization in source samples.  Same definitions apply to mr_weight_tgt.

Feel free to try to set mr_weight_tgt = 1.0.

**Comment by xiaoaoran** [comment]
Thank you.
